# Choose an agent virtual image
pool:
  vmImage: ubuntu-16.04
container:
  image: eschnett/simulationio-deps

steps:
- script: |
    set -euxo pipefail
    mkdir build
    cd build
    cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_MPI=OFF -DENABLE_RNPL=OFF -DENABLE_TILEDB=OFF -DCMAKE_INSTALL_PREFIX="${HOME}" ..
    make -j$(nproc)
  displayName: Build
- script: |
    set -euxo pipefail
    cd build
    make -j$(nproc) test CTEST_OUTPUT_ON_FAILURE=1
  displayName: Test
- script: |
    set -euxo pipefail
    cd build
    make -j$(nproc) install
  displayName: Install
